### ISSUE TITLE
web-cli: Bad prompt (y/Y)

### ISSUE THREAD

**Issue by hmil** [lbarman/vaultage#101]
When removing, the cli asks:
```
Confirm removal of entry #1 ? y/Y
```
(yes or yes, defaults to yes)?

**Comment by lbarman** [comment]
well I agree the notation is unconventional. [y|Y] yield "yes", anything else yields "no". Default is "no".

**Comment by lbarman** [comment]
Fixed af8230fc0af05e8ef829a8a5079e0328c4b572cf
