### ISSUE TITLE
Express makefile dependency between UI and client

### ISSUE THREAD

**Issue by hmil** [lbarman/vaultage#111]
`make` in the UI package does not depend on `vaultage-client` and may fail (top-level make does express the dependencies correctly).

Investigate if there is a way in Make to express the dependency from within the ui child project.

**Comment by lbarman** [comment]
Currently `make` and `make serve` do not rebuild the front-end on changes (which would be expected). I'm adding this as a `high-priority` *after* the `v4`

**Comment by hmil** [comment]
This is going to be a problem for deployment as we want a way to build ever

**Comment by hmil** [comment]
misclick sorry

**Comment by lbarman** [comment]
Done 421795aba3b0b8371936027a80f47c7f3ee44465
