### ISSUE TITLE
What happens when we delete cipher.json ?

### ISSUE THREAD

**Issue by lbarman** [lbarman/vaultage#113]
What is the default password ? It seems it does not get created automatically.
Let's create one with the accesses `user:password`

**Comment by hmil** [comment]
The behavior is to set [return an empty DB if it does not exist](https://github.com/lbarman/vaultage/blob/53d5c4cb6016c4d6cd160a7a6575fedef2064470/packages/vaultage/test/JSONDatabase.spec.ts#L64) and [not checking the password when writing out](https://github.com/lbarman/vaultage/blob/53d5c4cb6016c4d6cd160a7a6575fedef2064470/packages/vaultage/test/JSONDatabase.spec.ts#L153).

This allows the user to effectively set the password the first time the cipher is pushed. It may not be very idiomatic but it's cheap and does the job.

**Comment by lbarman** [comment]
Works as intented.
