### ISSUE TITLE
Check config persistance against app updates

### ISSUE THREAD

**Issue by hmil** [lbarman/vaultage#114]
Context: 
- We want to deliver the app as a global npm package.
- The cipher and config files are stored at the root of the package.

Question:
What happens when the package gets updated? Does this remove the config files?
If so, we might need to store those files at another OS-specific location (examples could be `/etc/vaultage` on unix, `%AppData%` on windows, or `~/.vaultage`)

Relevant SO thread https://stackoverflow.com/questions/19275776/node-js-how-to-get-the-os-platforms-user-data-folder

**Comment by lbarman** [comment]
Done fb6d61e5d75d88ddfc640f9b3998d2fa84fa292e
