### ISSUE TITLE
Target unification

### ISSUE THREAD

**Issue by lbarman** [lbarman/vaultage#118]
Are we targetting ES5 or ES6 ? It seems we recently moved to ES6 (hence some new bugs). We should check that we target the same for all modules.

It is worrying that those bugs (e.g. the `gen` command) are not catched by our current tests.

**Comment by hmil** [comment]
https://github.com/lbarman/vaultage/blob/v4.0/packages/vaultage/tsconfig.json#L9
https://github.com/lbarman/vaultage/blob/v4.0/packages/vaultage-client/tsconfig.json#L8
https://github.com/lbarman/vaultage/blob/v4.0/packages/vaultage-ui-webcli/tsconfig.json#L9

All packages target `es5`. There may be issues if some TS source lives outside the folders specified in `include` in which case the tsconfig.json does not apply to them.

**Comment by lbarman** [comment]
I'm pretty sure I had a bug related to ES6. Lemme investigate.

**Comment by lbarman** [comment]
Bug was unrelated; other bug fixed in 3aa31a002e80adc0988e449ea597fa87b982edca
