### ISSUE TITLE
Add user-friendly introduction

### ISSUE THREAD

**Issue by lbarman** [lbarman/vaultage#119]
Trouble beginning? First `auth` (at first, any password works), then `ls`. Try to `gen` a password, then `get` it. Try to `rotate` this entry, perhaps `edit`.

**Comment by hmil** [comment]
I don't see this as a `v4` blocker, more like a nice to have.

**Comment by lbarman** [comment]
It already took more time to discuss it than to do it. It was just a reminder for me ;)

**Comment by lbarman** [comment]
Done 962c7a2
