### ISSUE TITLE
Review of documents

### ISSUE THREAD

**Issue by lbarman** [lbarman/vaultage#121]
I just finished CONTRIBUTING.md and SYSTEM_DESIGN.md, your inputs are welcome:)

**Comment by hmil** [comment]
Three months later, here I am!



## SYSTEM_DESIGN.md :100: :1st_place_medal: 

> 2. S sends the latest Vaultage client to U, **as long as**

appears twice. Not sure if this is some leftover text.

> The user is prompter for its master password MP

prompter -> prompted ; its -> his/her

> This ensure all updates are sequential, to the cost of possibly denying an update to the user U.

In practice this is not a problem as changes are synchronized as soon as they are made (this project is offline-crypto, not offline-UX).

> U sees that there is nothing to decrypt, and initialize an empty local database DB.

initialize**s**

> No 3rd parties, including A, can retrieve {P} from data at in transit

-- at


## Contributing.md

[updated inline](https://github.com/lbarman/vaultage/commit/11d9b7e581423845021daffd408e12ccc01bf2f5)

**Comment by lbarman** [comment]
Thanks for the review !
Closing https://github.com/lbarman/vaultage/commit/d89e9818521f28b5621056c6514669d81153f0e3
