### ISSUE TITLE
Unit test initConfig

### ISSUE THREAD

**Issue by hmil** [lbarman/vaultage#122]
Test regression of https://github.com/lbarman/vaultage/commit/05dc390cab64ba7825873a3b16ddfbb3047a4afe

Should only need `SALT_LENGTH` bytes of random to generate two salts as explained in the comment but most of all needs testing to be sure we don't write bs.

**Comment by lbarman** [comment]
I am not sure I understand :>) Let's keep the units of length as "bits" or "bytes", not "hexadecimal".
Then if each salt is 32 bytes long, we need 2*32 bytes of randomness. Did I miss something ?

**Comment by hmil** [comment]
iirc salts are treated as strings hence `SALT_LENGTH` is a string length. Incidentally we use the hex representation of random bytes to generate crypto-secure salts as it is the easiest way to transfer entropy from Node.JS' crypto-randomness source to a string. So in the end we need half the string length bytes to generate a salt, no matter what we name the variables.
