### ISSUE TITLE
bug: in make, inconsistent fail

### ISSUE THREAD

**Issue by lbarman** [lbarman/vaultage#129]
Sometimes `make` fails with 

```
ERROR in /home/jwhite/d/git/vaultage/packages/vaultage-client/integration-test/integration-test.ts
[tsl] ERROR in /home/jwhite/d/git/vaultage/packages/vaultage-client/integration-test/integration-test.ts(4,37)
      TS2306: File '/home/jwhite/d/git/vaultage/packages/vaultage-client/vaultage.ts' is not a module.
```

Seems to be fixed by running `make clean && make cleanall` before hand

**Comment by hmil** [comment]
We need to move `vaultage-client/vaultage.ts` into `vaultage-client/src/vaultage.ts` and ffs just hardcode it instead of having the makefile generate it.

todo list (off the top of my head):
- [ ] move vaultage.ts to src/vaultage.ts
- [ ] remove anything in the makefile relating to generating vaultage.ts
- [ ] remove vaultage.ts from the .gitignore

**Comment by lbarman** [comment]
In the meantime, it has been fixed with a `.PHONY` and some quotes. ad6ba796fb40888bf4e1cbbb03dce49622cc3996

**Comment by hmil** [comment]
> In the meantime, it has been fixed with a .PHONY and some quotes. ad6ba79

I'm pretty sure this is unrelated, cf. my edit above.

Plus a .PHONY here is wrong because $(INDEX) is a real file.

**Comment by lbarman** [comment]
``` In terms of Make, a phony target is simply a target that is always out-of-date, so whenever you ask make <phony_target>, it will run, independent from the state of the file system```
Not super clean, but .PHONY isn't restricted to non-files

**Comment by hmil** [comment]
Right, however in this case the dependencies of `$(INDEX)` are already properly defined (using `$(SRC)`). Also the change of quote, although it makes the code more readable, doesn't seem to do any difference at execution time.
All in all I think the ad6ba79 doesn't do anything and it likely appeared to fix the issue by pure chance.

**Comment by lbarman** [comment]
> All in all I think the ad6ba79 doesn't do anything and it likely appeared to fix the issue by pure chance.

On my system (fedora & zsh) and on travis (ubuntu and bash I think), performing `make test` then `make` would fail because `packages/vaultage-client/vaultage.ts` would be empty, and `make` would not rebuild it. The `.PHONY` forces the rebuild, then I think you missed a `\` before the first `;` in the do while.

**Comment by lbarman** [comment]
Removes useless .PHONY 122589bf7816e1528d0592dab282751ee8844281
