### ISSUE TITLE
API enhancement / discussion

### ISSUE THREAD

**Issue by hmil** [lbarman/vaultage#138]
I don't think there is value in having the `Vault` object potentially unauthenticated. IMO we should refactor the API as follows:

```typescript
/** Current API: **/
const vault = new vaultage.Vault();
vault.auth(...);
// vault is eventually "authenticated"

/** Proposed change: **/
const vault = await vaultage.auth();
// vault is _necessarily_ in the "authenticated" state
```
This would allow us to remove a lot of `if (authenticate)` checks in the `Vault` class and make both sides (user & developer) of the API less error prone.

**Comment by lbarman** [comment]
sounds good !
