### ISSUE TITLE
Latest NPM build ignores the default username in config

### ISSUE THREAD

**Issue by lbarman** [lbarman/vaultage#140]
Perhaps this should be included / done after https://github.com/lbarman/vaultage/issues/136.

One problem is that the config file is not testable, and magically generated by the server *when it does not exists*, but re-read otherwise; plus, we cannot set the "username" from within vaultage at all. One solution would be to have a route `/updateConfig` that we could test in the `integration-test`

**Comment by hmil** [comment]
```
One solution would be to have a route /updateConfig that we could test in the integration-test
```
Another solution, which is much simpler, is to store the client-specific config in the browser's local storage.

**Comment by lbarman** [comment]
I agree, IMO perhaps the only thing that need to come from the server are the salts, and the "soft" user config can be indeed stored in the localStorage

**Comment by hmil** [comment]
closing in favor of #146
