### ISSUE TITLE
Refactor client config

### ISSUE THREAD

**Issue by hmil** [lbarman/vaultage#146]
Current meccanism to get the web-ui config is ugly.

I don't see why we can't use the localStorage to store the default username? cc @lbarman

**Comment by lbarman** [comment]
Agreed, except for the salts that need to come from the server (should they not exist in the localStorage)

**Comment by hmil** [comment]
They are now part of the vaultage protocol and are no longer exposed to the applications. They are now two distinct configs: The client application config (cosmetic things like default username) and the core config (salts and other protocol-related settings).
