### ISSUE TITLE
Feature proposal: session time-out

### ISSUE THREAD

**Issue by hmil** [lbarman/vaultage#151]
In the webui, add an opt-in feature to time the session out.

## Motivation

If I let a browser tab open and leave my computer unattended (and forget to lock it), I don't want people to be able to access all of my passwords.  
I don't want to `log-out` explicitly every time I use Vaultage and I don't want to re-type my username (painful extra keystrokes)

## Overview

The user sets a timeout value using a dedicated command. If no user input is received for that duration, the application unauthenticates, clears the screen and asks for the master password again in order to unlock the vault. The timeout value is persisted with the application configuration.

### web-ui changes

1. A new config variable `timeout_time: number | undefined`
2. A global variable `timeout_trigger` of the type returned by `window.setTimeout`
3. A hidden shell command `timeout_call` defined below (it cannot be invoked from the command line and is not referenced)
4. A new command `timeout` defined below
5. A function `timeout_reset`
6. Whenever the shell receives a user input, call `timeout_reset`
7. A `MIN_TIMEOUT` constant to prevent self lock-out by setting to low timeout values

### `timeout_call` (hidden shell command)

1. save the current vault's username in a local variable
2. log out (clear the screen and remove all references to the current vault)
3. show a password prompt
4. attempt a login with the username variable and provided password
5. if the login is successful, saves the new vault in the global context and exit
6. if the login is unsucessful, go back to 3.

(note: since this is a shell command, if the user cancels (ESC or C^c) the prompt, the shell goes back to its initial, unauthenticated state)

### `timeout` (shell command)

**The `config` command replaces this command**

- ~~Synopsis: `timeout <action>`~~
- ~~Actions:~~
    - ~~`set <time>` sets the `timeout_time` value according to the `time` format spec and transformation described below and resets `timeout_trigger`.~~
    ~~If `time` is zero, transform it to `undefined`  
    If `time` is less than MIN_TIMEOUT, throw an error
    else convert time to milliseconds~~
    - ~~`reset` sets `timeout_time` to `undefined` and clears `timeout_trigger`~~

#### `time` format

- define units = { 'h': 3600, 'm': 60, 's': 1 }
- input is `0` => output is `0`
- input matches `/(?value:\d+)(?unit:h|m|s)|0/` => output is `value * units[unit]` seconds

### `timeout_reset` (context method)

```
if timeout_time is not undefined:
  clear timeout_trigger
  set timeout_trigger = setTimeout(timeout_call, timeout_time)
```

**Comment by lbarman** [comment]
Agreed !
Let's have `timeout_time` be either `>30sec` to prevent self-lockout or `-1` to disable the feature.
