### ISSUE TITLE
Scale README.md screenshots

### ISSUE THREAD

**Issue by hmil** [lbarman/vaultage#152]
**problem**
Screenshots shown in README.md are too wide (>1000px) and suffer scaling issues when displayed on github.

**solution**
Figure out the optimal width of images to show on github. Take new screenshots with at most that width so they are not downscaled when shown

**Comment by lbarman** [comment]
Could you provide a screenshot of the screenshot so I see the problem ?

**Comment by hmil** [comment]
![we need to go deeper](http://i0.kym-cdn.com/entries/icons/original/000/012/886/wntgd.jpg)

**Comment by hmil** [comment]
Compare the screenshot [here](https://github.com/lbarman/vaultage/wiki/How-to-migrate-from-LastPass#step-2-upload-your-passwords-to-vaultage) (renders at 100% scaling, no crappy blur) with the ones [on the homepage](https://github.com/lbarman/vaultage) (appears blurry)

**Comment by hmil** [comment]
Empirical measurement suggests images on the homepage render at 888px width, in the wiki they render at 700px width. Anything greater than that will look crap.

**Comment by lbarman** [comment]
> (appears blurry)

Not on my machine. :)
Perhaps we could also improve and switch to an [https://asciinema.org/](Asciinema)
