### ISSUE TITLE
replace Sha1 by bcrypt

### ISSUE THREAD

**Issue by lbarman** [lbarman/vaultage#29]

**Comment by DaniellMesquito** [comment]
What do you think about MD5 or SHA256?

**Comment by lbarman** [comment]
MD5 isn't safe anymore. I would have gone for SHA256, but I'm not sure if bcrypt offers any advantage.
I'm also considering PBKDF2 : https://gist.github.com/scotttam/1149256

**Comment by lbarman** [comment]
Switched to SHA256. Will do for now :)
Fixed in 040ff3e69338ee89cb1c2f2e4dd86a4286be6c92
