### ISSUE TITLE
Graphical User Interface

### ISSUE THREAD

**Issue by Plasmmer** [lbarman/vaultage#34]
This will be very good.

**Comment by lbarman** [comment]
Not on my priority list, as I prefer text-based environments. Yet it would be good for novice users, should we want a bigger user base

**Comment by Plasmmer** [comment]
@hmil, what do you think about?

**Comment by lbarman** [comment]
What GUI do you have in mind exactly ?

**Comment by hmil** [comment]
@Plasmmer I wouldn't use it so I won't code it.

**Comment by Plasmmer** [comment]
@lbarman
> What GUI do you have in mind exactly ?

A GUI to reach more users, inspired by LastPass/KeePassX and others. To also be usefull in mobile devices.

**Comment by lbarman** [comment]
OK, then it's #90 for mobile. For the purely web+desktop based client, I wouldn't use a GUI. Plus, we now have the chrome-extension that is also a GUI.

Closing, but you're welcome to do a PR if you have something in mind
