### ISSUE TITLE
Support Cordova

### ISSUE THREAD

**Issue by Plasmmer** [lbarman/vaultage#35]
With this, the app will can work on:
- [ ] Android
- [ ] iOS
- [ ] Windows

**Comment by lbarman** [comment]
Would require switching to a nodejs app. Would solve https://github.com/lbarman/vaultage/issues/24 with packet https://nodejs.libhunt.com/project/clipboard-cli

**Comment by lbarman** [comment]
Won't do, mobile app is on its way
