### ISSUE TITLE
Security audit

### ISSUE THREAD

**Issue by hmil** [lbarman/vaultage#39]
Here is a list of weaknesses and fixes:
- Everything is web-accessible. A server misconfig could easily leak DB credentials and config data from web-accessible php files.
  **fix:** create a dir named `public` or `www` containing all and only the assets intended to be accessed from the web. Anything above this folder is therefore not accessible from the web. See the [laravel dir structure](https://github.com/bestmomo/laravel5-example) for a good example.
- **reset.php** should be authenticated. Currently an attacker can issue a CSRF attack from any web page he is able to inject scripts into. Example: visiting [this page](https://people.epfl.ch/hadrien.milano?lang=fr) resets the demo vault.
  **fix**: only allow auth'ed user to execute the reset command.

**Comment by lbarman** [comment]
I agree with "reset.php", which I initially only added for the demo website; it should not be there for non-demo sites. It was meant for a cron job that runs every midnight, and on the demo site, if run more frequently, it does not matter.

I don't see the issue with "everything is web-accessible". What is your suggestion for having AJAX requests ? those pages need to be readable by Apache

**Comment by hmil** [comment]
> I don't see the issue with "everything is web-accessible". What is your suggestion for having AJAX requests ? those pages need to be readable by Apache

If you have the following directory structure:
```
-+ vaultage/
 +-+ public/  # <- serve this
 | + index.html
 | +-+ css/
 | |    
 | +-+ js/ # client-side JS
 | |       
 | +-+ ajax/
 |   +- do.php
 +- config.php
 +- setup.php
```
Then when a browser hits /ajax/do.php, php will be able to resolve `include('../../config.php')` but the client will not be able to hit directly "config.php" from the web.

Better yet, if you want to make the web-cli optional, you can do something like:

```
-+ vaultage/
 +-+ api/  # <- serve this
 | +- do.php
 +-+ clients/
 | +-+ web-cli/ # <- optionally serve this if you want the web-cli
 | | + index.html
 | | +-+ css/
 | | |   
 | | +-+ js/ # client-side JS
 | |
 | +-+ node-js/ # <- This would contain the source code for the node-js client
 | | +- package.json
 | |
 | +-+ chrome-ext # <- And for a chrome extension
 | |
 | +-+ # ... You get the idea
 |
 +- config.php
 +- setup.php
```

Then it depends on your repo management policy, you might want to do something else in the same spirit.

> I agree with "reset.php", which I initially only added for the demo website; it should not be there for non-demo sites. It was meant for a cron job that runs every midnight, and on the demo site, if run more frequently, it does not matter.

This script could also be located outside the web-served directory and the cron job would run `php /path/to/reset.php` instead of the `curl http://localhost...` that is likely currently being used.

**Comment by lbarman** [comment]
Sounds good. Thanks for the detailed explanation.

> This script could also be located outside the web-served directory and the cron job would run php /path/to/reset.php instead of the curl http://localhost... that is likely currently being used.

No, I didn't rely on curl, the file was placed there so I could install vaultage with `git clone` (and the whole git dir was the equivalent of `www`). Your structure makes more sense.

**Comment by lbarman** [comment]
Fixed https://github.com/lbarman/vaultage/commit/06cdd6b23f7446720b9fff9086b3561770ae0440. Thanks
