### ISSUE TITLE
Implement token based auth mechanism

### ISSUE THREAD

**Issue by hmil** [lbarman/vaultage#53]
A better way to handle "saved" authentication is to have the server issue auth tokens. These auth tokens have an expiration date and can be revoked.

Some of the advantages provided by this feature:
- The client discards the remote password once auth is done (preventing theft)
- This allows to create at least two security rings for use actions:
  - _ring 1_ for basic authenticated actions (pull the cipher, update it)
  - _ring 2_ for sensitive actions (update the remote password, manage tokens)
    Ring 2 requires a valid auth token AND the remote password (since the client discards the remote password, the user has to re-type the master key to perform those actions).
- Easier interfacing with 2FA providers

**Comment by lbarman** [comment]
Yep, and it also prevents replay attack in the case someone deploys it on HTTP... eventough this is not in our threat model ;)

**Comment by lbarman** [comment]
Can we close the issue ?

**Comment by hmil** [comment]
Yes, doesn't seem like this is going to be implemented anytime soon.

**Comment by lbarman** [comment]
MB, I thought it was the TOTP. Let's keep it open.
I also want the project to remain concise and easy to understand; I want to carefully evaluate the complexity of this (and removing the old method) before going for it. That means fixing all the current bugs/todos and reaching a clean state first :)

**Comment by hmil** [comment]
Less relevant with #151
