### ISSUE TITLE
Do not trust CAs

### ISSUE THREAD

**Issue by hmil** [lbarman/vaultage#54]
Certificate authorities have been compromised in the past.

-> Implement private key crypto within the app to add an additional layer of security not tied to SSL but instead relying on a certificate built into the client. The app could then even be used over a non-secure transport channel (HTTP) provided that the client binary was obtained in a trusted way.

-> Kinda hard to do it right :/

**Comment by lbarman** [comment]
what are you trying to prevent ?

"private" key crypto -> symmetric key crypto ? Then you have a bootstrapping problem, as the initial delivery cannot be legitimately more secure than over HTTPS. So you trust CAs anyway ;)

**Comment by hmil** [comment]
If the application-level certificate is bundled with the client, then both the HTTPS channel and the update channel for your client have to be compromised.

In the case of a web client, the "update" channel is the HTTPS channel itself so there is little to no benefit indeed.

**Comment by lbarman** [comment]
> If the application-level certificate is bundled with the client, then both the HTTPS channel and the update channel for your client have to be compromised.

How will you deploy this application ? Users wanting to install it from github (or npm package) rely on HTTPS security anyway, so there's no added security in building a layer on top. If you don't trust HTTPS, then the whole source code cannot be trusted if distributed via github
