### ISSUE TITLE
Fix the web-ui

### ISSUE THREAD

**Issue by hmil** [lbarman/vaultage#63]
I broke some of the UI and maybe a couple features while refactoring the core framework for v3.
However, as I am mostly using the chrome extension and as the web-ui still does what I need it to do, I won't spend time rounding off the edges on that one.

**Comment by lbarman** [comment]
Sure. I'll spend more time playing around with v3, but it looks pretty mature. I'm for merging it into master soon.

**Comment by lbarman** [comment]
TODO: 2FA into web-cli

**Comment by lbarman** [comment]
To be done after #46 , which will be my playground for testing the new `Vault`

**Comment by lbarman** [comment]
Fixed with `v4`
