### ISSUE TITLE
PBKDF2 Iterations

### ISSUE THREAD

**Issue by lbarman** [lbarman/vaultage#70]
@hmil , where does the 32768 iterations = 2^15 (default value) for PBDKF2 comes from ? Is it arbitrary ?

**Comment by hmil** [comment]
Yes, I'm aiming for between 200ms and 1s of run time on commodity hardware nowadays which makes any brute force attack impractical for the foreseeable future while still being OK from a UX perspective.

**Comment by lbarman** [comment]
I'd tune it down a bit (<100 ms) since the UI freezes during that time. Generally speaking, I don't think bruteforcing the hash will be a likely possibility, especially with good salts.

**Comment by hmil** [comment]
A better alternative IMO would be to do the computation in a background thread while the UI shows a spinner. This is fairly straightforward to do with web workers and as far as I'm concerned I can expend this little bit of time for enhanced security. Especially given that we do not know how the computing power will evolve in the future, better be as safe as possible right now.
