### ISSUE TITLE
public directory misses a .php

### ISSUE THREAD

**Issue by lbarman** [lbarman/vaultage#71]
Once `make` has run in the root folder of the repo, the `public` directory looks like:

```
public
- api
--- index.php
- web-cli
--- index.html
--- ...
```
In `index.html`, the API_URL is defined as `./api/index.php` (either it misses one dot, or we miss a php redirection in public)

**Comment by hmil** [comment]
That's because of the way the web server is set-up (see docker-nginx).

It might be easier though to just serve the public/ directory as a whole. Feel free to refactor.

**Comment by lbarman** [comment]
Done 95b93801935741dd1bf66498b00368728e3b2af9
