### ISSUE TITLE
Cipher bigger than expected

### ISSUE THREAD

**Issue by hmil** [lbarman/vaultage#81]
In my tests while importing some data I got a ciphertext of ~ 100KB . This is too large for the mysql column type `TEXT` and we should use `LONGTEXT` instead.

The second problem is that if we keep our "append-only" strategy, we'll end up with a huge DB in no time...

**Comment by lbarman** [comment]
Indeed.
In the original version, I wasn't keeping the history. Maybe we could keep X=2 ciphers, in case one goes wrong .. (but this shouldn't happen with the PBKDF chaining)
