### ISSUE TITLE
Testing & CI

### ISSUE THREAD

**Issue by lbarman** [lbarman/vaultage#91]
In terms of priority:
1. The `Vault` and `Crypto` class
2. The web-cli (maybe by simulating interaction ?)
3. chrome-ext, mobile-cli, urgencedecryptor-cli

**Comment by lbarman** [comment]
Fixed with `v4`, do the CI

**Comment by hmil** [comment]
plz enable CI [here](https://travis-ci.org/lbarman/vaultage)

**Comment by lbarman** [comment]
Done
