### ISSUE TITLE
Folder structure still too complex

### ISSUE THREAD

**Issue by lbarman** [lbarman/vaultage#92]
What about having a `src` folder with all the build stuff, and a `packed` or `bin` or `stable` folder with the compiled, ready-to-deploy bins ?

In this `stable` folder, we'd have something like 
```
- server
- web-cli
- mobile-cli
- chrome-cli (possibly just the .crx)
```

all mignified, and with all dependencies. We would only change it for major releases and critical fixes.

What do you think @hmil ?

**Comment by hmil** [comment]
:+1:

**Comment by lbarman** [comment]
OK. Also is there a security advantage to have `public/api/` server, that just includes `../server/app.php` ? Could we merge this into one ? Those `goto` are quite confusing

**Comment by hmil** [comment]
The idea is that if you deploy like it is deployed with the docker-based turnkey solution, then the web server can't even read the config files (because nginx is "sort-of-chrooted" to `public/`).

Though iirc this makes it harder to deploy Vaultage on an old-school FTP+LAMP stack so I'm not sure the security benefit outweighs the added complexity anymore.

**Comment by lbarman** [comment]
Yep... The docker-turnkey is almost perfect, but if you don't have a reverse proxy, it's a mess to give it a correct certificate. On my server, I'll keep my barebone apache server, and serving directories seems simple enough. 
Maybe I'll make a Apache `site` config, allowing to clone vaultage to `opt/` and "serve everything", except the readable folders would be manually specified in the `site` config. We'd rely on Apache instead of docker's `chroot`, but this looks safe enough to me

**Comment by hmil** [comment]
Not sure though about the global `dist` folder.

Having one `dist` per package seems easier to manage imo and you can still leverage GitHub's [releases](https://help.github.com/articles/creating-releases/) to expose useful build artifacts for each release.

**Comment by lbarman** [comment]
The idea would be to put everything we have now in `src`, including the ability to create `dist` in this `src`. This would be the buildable, rolling source. The global `dist` would be `make`able but would contain stuff strictly useful to the guy that wants to *deploy* it, without rebuilding.
We could hide this nasty `vendor` folder in `src` too.

**Comment by lbarman** [comment]
OK maybe we don't need the already-built folder, if it's just one `make` away.

In my PR #90 , I put the `server` into `packages` (which I would like to ultimately like to call `src`). We still have this ugly `vendor/` folder, how do you build it btw ?

**Comment by lbarman** [comment]
OK maybe we don't need the already-built folder, if it's just one `make` away.

In my PR #90 , I put the `server` into `packages` (which I would like to ultimately like to call `src`). We still have this ugly `vendor/` folder, how do you build it btw ?

**Comment by lbarman** [comment]
Fixed with `v4`
