### ISSUE TITLE
Backup import export

### ISSUE THREAD

**Issue by lbarman** [lbarman/vaultage#93]
The email backup functionality is working, but not very practical to migrate data. It would be nice to have a clean .json to input/output.

I think the best choice is still to encrypt it like vaultage does for the ciphers (this would be the equivalent of a db dump, but with a possibly different password, and the import would merge the actual and imported data).

The simplest path would be to add `import(db, pwd)` and `export(pwd)` functions to `Vault`

**Comment by hmil** [comment]
Currently working on a CSV import feature on [import-csv](https://github.com/lbarman/vaultage/tree/import-csv)

**Comment by lbarman** [comment]
That might be fine. The use case I was considering is to move from my current vaultage instance to the next v3.

**Comment by lbarman** [comment]
Done in v4
