### ISSUE TITLE
v4 planning

### ISSUE THREAD

**Issue by lbarman** [lbarman/vaultage#96]
tag @hmil 

Let's discuss and sort the *features* we want from v4. After, we'll come up with a design.

My approach:
- Secure by default: let's focus on a simple, unique setup (docker + tls reverse proxy) that just works well for anyone. People that want Apache can adapt the code
- Simple to deploy (docker + tls reverse proxy is the limit)
- Simple stack: let's see with couchDB and a single frontend (if possible compatible mobile)
- Modular login/encryption keys (if you want to use MFA, you should be able to do it simply)

If CouchDB exposes a REST API, that's great, we just need to find out how to auth before getting the ciphertext. Or, we don't auth but put an .htaccess in the front-end, and make couchDB only visible to the docker image.

**Comment by lbarman** [comment]
I'd by to ditch php/mysql, and have a full JS/typescript stack. MongoDB seems adapted as a DB

**Comment by lbarman** [comment]
Ideally, we should have the following separation:
1. UI for the client that interacts with Vaultage lib
2. Vaultage lib that interacts with the DB
3. Dumb db that only stores one thing

**Comment by lbarman** [comment]
In terms of security, we assume that the server on which Vaultage runs is honest-but-curious. We cannot protect against a malicious server from the browser. Yet we don't need to fully trust the server.

The server runs two docker:
1. TLS Reverse proxy with HTTP Basic auth (provides authentication and confidentiality)
2. Vaultage docker that serves the code and the db cipher to the client through the reverse proxy

**Comment by hmil** [comment]
Could be even simpler. IF we are willing to rely on couchdb's SSL, then the backend is either a plain couchdb instance, or a docker image based on couchdb's.

Another interesting feature is that couchdb can serve static content (known as "couch apps") and even though it is losing popularity because of people abusing the feature, we could leverage it to serve a front-end for free.

Another thing to consider is whether backend abuse (bruteforce, DDoS) is within the threat model.

**Comment by lbarman** [comment]
DECISION
1. Docker with TLS reverse proxy and authentication
2. Docker with NGINX serving static files (UI + VaultageCore) and CouchDB

VaultageCore in Typescript with tests

Folder structure for 2.
- core
- frontends
-- web
-- chrome-ext
-- mobile
Dockerfile
