### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by hmil** [lbarman/vaultage#99]
<details>
<summary>Screw that stuff</summary>
Ideal setup is:

On travis-ci:
```
Run the tests
if success AND current branch is release branch:
  build each package for production
  publish each package
```

If we agree to stick to the [conventional changelog](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md) format for commit messages, then we can have travis figure out the proper semantic version of the next release using commit messages only. Writing conventional commit messages is a breeze thanks to packages which integrate tightly into git.

The case for automated releases is that it saves the developer time and effort as publishing a module is tedious and if done incorrectly can lead to bad releases and futher time lost fixing it.
The case against automated releases is that it takes time to set up the system itself. Also careless versioning and improper backwards compatibility testing may result in the accidental publishing of breaking releases.

Based on my experience with [topside](https://github.com/hmil/topside) (nodejs, conventional-changelog, automatically published) and [RosHTTP](https://github.com/hmil/RosHTTP) (scala, manual publish to sonotype nexus), the peace of mind and time saved at the end is well worth the effort put at the beginning.
</details>

---

Considerations:
- do not ship test js files (useless)
- enforce build and test of everything before shipping
- insert dependencies in package.json (~~see if we can leave the deps permanently or if this causes troubles with the build system~~ -> it does)
- bump version in package.json (do we want lock-step versioning? probably yes)

Implementation:
- node (shelljs?) script. top-level package.json for this script's deps. maybe add target to makefile
- script asks for version
- good to have: script prepares a github release.

Don't do on CI for now, just ship from dev localhost.

**Comment by lbarman** [comment]
I'm not fully convinced, but we could try.
Is your experience of writing "conventional" git messages limited to those four commits ? [https://github.com/hmil/topside-vscode/commits/master](https://github.com/hmil/topside-vscode/commits/master). The immediate downside is that those are not super clear for an outsider. But hey who would read our commit anyway
Do you know to which extend this convention is used ?

**Comment by hmil** [comment]
More like having automated  [those 18 releases](https://github.com/hmil/topside/releases) with proper semantic versioning.
It is pretty widely spread and gaining popularity thanks to angular among others.

**Comment by lbarman** [comment]
Okay, cool. And say my second personality takes over, and I accidentally push a commit named "Changes", what happens? Is there a failsafe?

**Comment by hmil** [comment]
Your commit would be rejected by git. Then if you somehow found a way to push it, then the build would fail saying you need to fix the history in order for the system to figure out the correct version number.

Maybe a good compromise would be to have travis push the changes but figure the version using manually input git tags. I still see value in automating the release but I'm not sure if the conventional changelog approach would fit this project well.

**Comment by lbarman** [comment]
Closing, follow-up in https://github.com/lbarman/vaultage/issues/117
